server:
  port: 8080

spring:
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  application:
    name: park-api
  datasource:
    url: jdbc:mysql://localhost:3306/park-api-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bahia
    username: alirio-dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /docs-park-api.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /docs-park-api
  packagesToScan: br.com.example.park_api.web.controller

logging:
  level:
    root: info
    org.springframework: info