services:
  mysql:
    image: mysql:latest
    container_name: park-api
    ports:
      - "3306:3306" # DB main
    environment:
      MYSQL_ROOT_PASSWORD: db-root-dev
      MYSQL_DATABASE: park-api-db
      MYSQL_USER: alirio-dev
      MYSQL_PASSWORD: dev
    volumes:
      - park-api-db:/var/lib/mysql
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: always

#  mysql-test:
#    image: mysql:latest
#    container_name: park-api-test
#    ports:
#      - "3307:3306" # DB test
#    environment:
#      MYSQL_ROOT_PASSWORD: db-root-dev
#      MYSQL_DATABASE: park-api-db-test
#      MYSQL_USER: alirio-dev
#      MYSQL_PASSWORD: dev
#    volumes:
#      - park-api-db-test:/var/lib/mysql
#      - ./database/init-db-test.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  park-api-db: {}
#  park-api-db-test: {}

# Abra um terminal no diretório do docker-compose e execute:
# docker-compose up -d